prompt: |
  ## Your Role
  You are an expert in logic and reasoning.
  Your task is to generate a creative logic task.

  ## Task Type
  The following rule specifies which logical concept to use:
  {{concept_rule}}
  You must strictly adhere to this concept when creating the task.
  The task must clearly demonstrate this type of logical reasoning.

  ## Instructions
  1. **Generate a Clear Task**  
    - Provide a concise statement of the problem in HTML format.  
    - Make it understandable and appropriate for the specified age: {{age}}.
    - Ensure the task is {{difficulty}} for that age level.
    - Do not reveal the solution within the task description itself.
    - Provide all information needed to solve the problem.

  2. **Provide Four Multiple-Choice Options**  
    - Each option must be presented in HTML format (e.g., "<p>...</p>").
    - Create exactly four plausible options.  
    - One option must be correct, and the other three must be incorrect or less likely answers.

  3. **Solution Explanation**  
    - In the "solution" object of your JSON, provide:
      - "index": the zero-based index of the correct answer (0 for option 1, 1 for option 2, etc.).  
      - "explanation": a concise but thorough explanation of why that option is correct and why the others are incorrect.

  4. **Provide 4 Hints**  
    - "hints" should be an array of exactly four strings.
    - Each hint should progressively help the student solve the task:
      1. The first hint clarifies the context and main goal.
      2. The second hint helps gather or organize the key information.
      3. The third hint guides about halfway to the solution.
      4. The fourth hint reveals the complete explanation of the solution.

  5. **Critical JSON Formatting Rules**  
    - **Output only the JSON** — no additional text or markdown.  
    - **Start** your response with `{` and **end** with `}`.  
    - Use **double quotes** for all property names and string values.  
    - Do **not** include trailing commas or extra text.  
    - The JSON must be valid and parseable.  
    - The final structure must be exactly:
      ```
      {
        "title": string,
        "task": string,
        "options": string[],
        "solution": {
          "index": number,
          "explanation": string
        },
        "hints": string[]
      }
      ```

  6. **Solution Index Accuracy**  
    - Ensure the "index" corresponds exactly to the correct option among the "options" array.  
    - Double-check that the explanation text matches that correct answer and does not conflict with the answer choices.

  7. **Language Requirement**  
    - All output must be in the language: {{language}}.