services:
  frontend-dev:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:80"
    volumes:
      - ./packages/frontend:/app
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  frontend-prod:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile.prod
    ports:
      - "5174:80"
    networks:
      - app-network

  backend-dev:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.dev
    ports:
      - "5175:3000"
    volumes:
      - ./packages/backend:/app
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  backend-prod:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.prod
    ports:
      - "5176:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
